# Generated by Django 5.0.4 on 2025-10-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_users_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatorSettings',
            fields=[
                ('setting_key', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('setting_value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Simulator Setting',
                'verbose_name_plural': 'Simulator Settings',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('symbol', models.CharField(help_text='Stock ticker symbol (e.g., AAPL)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Company name', max_length=100)),
                ('current_price', models.FloatField(default=100.0, help_text='Current price per share')),
                ('previous_close', models.FloatField(default=100.0, help_text='Previous closing price')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this stock is available for trading')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['symbol'],
            },
        ),
        migrations.AlterField(
            model_name='users',
            name='cache',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='stockbuy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='stocksold',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='users',
            name='watchlist',
            field=models.JSONField(default=dict),
        ),
    ]
