# Generated by Django 5.0.4 on 2025-10-16 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_simulatorsettings_stock_alter_users_cache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Event name (e.g., 'Spring Trading Challenge 2025')", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description and rules')),
                ('start_time', models.DateTimeField(help_text='Event start date and time')),
                ('end_time', models.DateTimeField(help_text='Event end date and time')),
                ('initial_capital', models.DecimalField(decimal_places=2, default=100000.0, help_text='Starting balance for each team', max_digits=12)),
                ('is_active', models.BooleanField(default=False, help_text='Is event currently active?')),
                ('registration_open', models.BooleanField(default=True, help_text='Can teams register?')),
                ('allow_short_selling', models.BooleanField(default=False, help_text='Allow teams to short sell?')),
                ('max_trades_per_team', models.IntegerField(blank=True, help_text='Maximum trades per team (leave empty for unlimited)', null=True)),
                ('trading_fee_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Trading fee as percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(help_text='Team name', max_length=100)),
                ('team_code', models.CharField(help_text='Unique team code (e.g., TEAM-X7K2)', max_length=20, unique=True)),
                ('password', models.CharField(help_text='Team password for login', max_length=128)),
                ('leader_name', models.CharField(help_text='Team leader name', max_length=100)),
                ('leader_email', models.EmailField(help_text='Team leader email', max_length=254)),
                ('members', models.JSONField(default=list, help_text='List of team member names')),
                ('balance', models.DecimalField(decimal_places=2, help_text='Current available cash', max_digits=15)),
                ('portfolio', models.JSONField(default=dict, help_text='Stock holdings: {symbol: {quantity: int, avg_price: float}}')),
                ('trade_history', models.JSONField(default=list, help_text='List of all trades')),
                ('total_trades', models.IntegerField(default=0, help_text='Total number of trades made')),
                ('is_active', models.BooleanField(default=True, help_text='Is team active in competition?')),
                ('is_disqualified', models.BooleanField(default=False, help_text='Has team been disqualified?')),
                ('disqualification_reason', models.TextField(blank=True)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('last_trade_time', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='app1.event')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['team_name'],
                'unique_together': {('event', 'team_name')},
            },
        ),
    ]
