# Generated by Django 5.0.4 on 2025-10-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_event_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(default='Technology', help_text='Industry sector', max_length=50),
        ),
    ]
