# Generated by Django 5.0.4 on 2025-11-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_stock_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulatorsettings',
            name='setting_key',
        ),
        migrations.AddField(
            model_name='simulatorsettings',
            name='setting_name',
            field=models.CharField(db_column='setting_name', default=1, max_length=50, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='simulatorsettings',
            table='app1_simulatorsettings',
        ),
    ]
