# Generated by Django 5.0.4 on 2025-11-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_simulatorsettings_setting_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='News headline', max_length=200)),
                ('content', models.TextField(help_text='Full news content/description')),
                ('impact_direction', models.CharField(choices=[('positive', '📈 Positive (Bullish)'), ('negative', '📉 Negative (Bearish)'), ('neutral', '➡️ Neutral'), ('mixed', '🔀 Mixed')], default='neutral', help_text='Overall market impact direction', max_length=10)),
                ('severity', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact'), ('critical', 'Critical Impact')], default='medium', help_text='How much this affects the market', max_length=10)),
                ('affected_sectors', models.JSONField(blank=True, default=list, help_text="List of sectors affected (e.g., ['Technology', 'Healthcare'])")),
                ('affected_stocks', models.JSONField(blank=True, default=list, help_text="List of specific stock symbols affected (e.g., ['AAPL', 'MSFT'])")),
                ('trading_hint', models.TextField(blank=True, help_text='Optional hint for traders about how to react to this news')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this news is currently visible to teams')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this news should stop being displayed (optional)', null=True)),
            ],
            options={
                'verbose_name': 'Market News',
                'verbose_name_plural': 'Market News',
                'ordering': ['-published_at'],
            },
        ),
    ]
