name: Update Stock Prices with Real Market Data

on:
  schedule:
    # Run every 1 minute during market hours for real-time updates
    # Covers: Pre-market (9 AM UTC = 5 AM ET), Regular hours, After-hours
    # Monday-Friday only (trading days)
    - cron: '* 9-21 * * 1-5'
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

jobs:
  update-prices:
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Stock Prices from Yahoo Finance
        run: |
          echo "🔄 Fetching real-time stock prices from Yahoo Finance..."
          echo "⏰ Current time: $(date -u)"
          
          # Call the real price update endpoint
          response=$(curl -s -w "\n%{http_code}" -X GET "https://tradesim-lyart.vercel.app/api/update-prices-real")
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n-1)
          
          echo "📊 Response:"
          echo "$body" | jq '.' || echo "$body"
          
          if [ "$http_code" -eq 200 ]; then
            echo "✅ Stock prices updated successfully!"
            # Extract success metrics
            updated=$(echo "$body" | jq -r '.updated_count // 0')
            total=$(echo "$body" | jq -r '.total_stocks // 0')
            echo "📈 Updated $updated out of $total stocks"
          else
            echo "❌ Failed to update prices (HTTP $http_code)"
            exit 1
          fi
